SAMPLES: config/samples.tsv
UNITS: config/units.tsv

OUTPUT:
    # REF: hg19  # TODO:
    RUN:
        QC: False
        PEAKS: False
        BWS: True
    BW_NORMALIZATIONS:
        - rawcount
        - FPM
    BAMPROCESS_PARAMS: -q 30
    MACS_THRESHOLD: 0.01

REF:
    NAME: hg19
    FA: /groups/lackgrp/genomeAnnotations/hg19/hg19.fa
    BWA_IDX: /groups/lackgrp/genomeAnnotations/hg19/hg19.bwa.idx
    CHROM_SIZES: /groups/lackgrp/genomeAnnotations/hg19/hg19.chrom.sizes

CUT_ADAPTERS: True
ADAPTER_FWD: CTGTCTCTTATA
ADAPTER_REV: CTGTCTCTTATA