SAMPLES: config/samples.tsv
UNITS: config/units.tsv

OUTPUT:
    RUN:
        QC: True
        PEAKS: False
        BWS: True
    BW_NORMALIZATIONS:
        - rawcount
        - FPM
    BAMPROCESS_PARAMS: -q 30
    MACS_THRESHOLD: 0.01

REF:
    NAME: hg38
    FA: /groups/lackgrp/genomeAnnotations/hg38/hg38.fa
    BWA_IDX: /groups/lackgrp/genomeAnnotations/hg38/hg38.bwa.idx
    CHROM_SIZES: /groups/lackgrp/genomeAnnotations/hg38/hg38.chrom.sizes

CUT_ADAPTERS: True
ADAPTER_FWD: CTGTCTCTTATA
ADAPTER_REV: CTGTCTCTTATA