SAMPLES: config/samples.tsv
GEOSAMPLES: config/geo_samples.tsv
UNITS: config/units.tsv

OUTPUT:
    REF: hg38
    RUN:
        QC: False
        PEAKS: True
        BWS: True
        CHIPATLASBED: False
        CHIPATLASBIGWIG: False
    BW_NORMALIZATIONS:
        - rawcount
        - FPM
    BAMPROCESS_PARAMS: -q 30
    MACS_THRESHOLD: 0.01
    CHIPATLASBED_THRESHOLD: '05'

REF_hg19:
    FA: /groups/lackgrp/genomeAnnotations/hg19/hg19.fa
    BWA_IDX: /groups/lackgrp/genomeAnnotations/hg19/hg19.bwa.idx
    CHROM_SIZES: /groups/lackgrp/genomeAnnotations/hg19/hg19.chrom.sizes

REF_hg38:
    FA: /groups/lackgrp/genomeAnnotations/hg38/hg38.fa
    BWA_IDX: /groups/lackgrp/genomeAnnotations/hg38/hg38.bwa.idx
    CHROM_SIZES: /groups/lackgrp/genomeAnnotations/hg38/hg38.chrom.sizes

CUT_ADAPTERS: True
ADAPTER_FWD: CTGTCTCTTATA
ADAPTER_REV: CTGTCTCTTATA

UPDATE_CHIPATLAS: False